version: '3'

services:

  php:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: Tns@2424**
      MYSQL_DATABASE: interapp
      TZ: Africa/Tunisia
    volumes:
    - mysql_data:/var/lib/mysql  # create a volume named mysql_data and mount it to the /var/lib/mysql directory inside the MySQL container, ensuring that data persists even if the container is removed.

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      UPLOAD_LIMIT: 512M
    ports:
      - "8081:80"
    depends_on:
      - mysql

volumes:
  mysql_data:  # define the volume mysql_data in your Docker Compose file

